from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Set
from uuid import uuid4

from .audit_logger import AuditLogger
from .phase11 import SellerOpportunity
from .phase25 import ActionForApproval, ApprovalStatus, HumanInTheLoopEngine
from .phase34 import (
    BuyerDealMatcher,
    DealContext,
    EnhancedBuyerProfile,
)


@dataclass
class OutreachDraft:
    """A professional, compliant outreach draft generated by the AI."""

    recipient_type: str  # 'buyer' or 'seller'
    subject: str
    body: str


class CommunicationContentAgent:
    """
    Phase 35: Generates professional and compliant outreach drafts.
    This agent does NOT send communications.
    """

    def generate_buyer_outreach_draft(
        self, deal: DealContext, buyer: EnhancedBuyerProfile
    ) -> OutreachDraft:
        """Generates an outreach draft for a matched buyer."""
        subject = f"Investment Opportunity in {deal.zip_code}"
        body = (
            f"Hello {buyer.name},\n\n"
            f"Our system has identified a new {deal.investment_strategy} opportunity "
            f"in {deal.zip_code} that aligns with your investment criteria.\n\n"
            f"This is a {deal.property_type} with an estimated purchase price of ${deal.purchase_price:,.0f}. "
            "Please note that all figures are estimates and subject to due diligence.\n\n"
            "If you are interested in learning more, please let us know.\n\n"
            "To opt-out of future communications, please reply with 'unsubscribe'."
        )
        return OutreachDraft(recipient_type="buyer", subject=subject, body=body)

    def generate_seller_outreach_draft(
        self, deal: DealContext, seller: SellerOpportunity
    ) -> OutreachDraft:
        """Generates an initial outreach draft for a potential seller."""
        subject = f"Regarding your property in {deal.zip_code}"
        body = (
            f"Hello,\n\n"
            "We are local investors interested in properties in your area and came across yours. "
            "We specialize in providing fair, as-is offers that can close quickly.\n\n"
            "If you have ever considered selling or would like to know what a no-obligation offer might look like, "
            "we would be happy to connect.\n\n"
            "To opt-out of future communications, please reply with 'unsubscribe'."
        )
        return OutreachDraft(recipient_type="seller", subject=subject, body=body)


@dataclass
class CommunicationResult:
    """The result of a communication attempt."""

    external_message_id: str
    status: str  # 'sent', 'failed', 'delivered'
    error_message: Optional[str] = None


class CommunicationProvider(ABC):
    """Abstract base class for communication providers (e.g., email, SMS)."""

    @abstractmethod
    def send(self, payload: Dict[str, Any]) -> CommunicationResult:
        """Sends a message."""
        pass


class MockCommunicationProvider(CommunicationProvider):
    """A mock provider that simulates sending communications."""

    def __init__(self, simulate_failure: bool = False):
        self.simulate_failure = simulate_failure

    def send(self, payload: Dict[str, Any]) -> CommunicationResult:
        """Simulates sending an email and returns a mock result."""
        print(f"MOCK_PROVIDER: Sending email to {payload.get('to')} with subject '{payload.get('subject')}'")
        if self.simulate_failure:
            return CommunicationResult(
                external_message_id=f"mock_msg_fail_{uuid4()}",
                status="failed",
                error_message="Simulated provider failure",
            )
        return CommunicationResult(
            external_message_id=f"mock_msg_sent_{uuid4()}", status="sent"
        )


@dataclass
class ContactHistoryRecord:
    """Records a single contact event."""
    timestamp: datetime
    action_id: str
    status: str # e.g., 'SUBMITTED_FOR_APPROVAL', 'SENT', 'FAILED'

class ContactProtectionService:
    """
    Phase 35: Provides safeguards for all outreach.
    """
    def __init__(self, db_client, audit_logger: AuditLogger, cooldown_hours: int = 24):
        self.db_client = db_client
        self.audit_logger = audit_logger
        self.cooldown = timedelta(hours=cooldown_hours)

    def _add_to_history(self, organization_id: str, entity_id: str, action_id: str, status: str):
        try:
            self.db_client.add_contact_history(organization_id, entity_id, action_id, status)
        except Exception as e:
            self.audit_logger.log("DB_ERROR", f"Failed to write contact history: {e}")

    def is_outreach_allowed(self, buyer: EnhancedBuyerProfile, organization_id: str) -> bool:
        """Checks opt-out status and rate limits."""
        # 1. Check for opt-out
        if self.db_client.get_opt_out_status(organization_id, buyer.buyer_id):
            self.audit_logger.log("CONTACT_PROTECTION_BLOCKED", f"Buyer {buyer.buyer_id} has opted out.")
            return False

        # 2. Check rate limit / cooldown
        last_contact_str = self.db_client.get_last_contact_timestamp(organization_id, buyer.buyer_id)
        if last_contact_str:
            last_contact_time = datetime.fromisoformat(last_contact_str)
            if datetime.utcnow() - last_contact_time < self.cooldown:
                self.audit_logger.log("CONTACT_PROTECTION_BLOCKED", f"Buyer {buyer.buyer_id} is within the cooldown period.")
                return False

        return True


class OutreachOrchestrationAgent:
    """
    Phase 35: Orchestrates the creation and submission of outreach actions for approval.
    """

    def __init__(
        self,
        matcher: BuyerDealMatcher,
        content_agent: CommunicationContentAgent,
        hitl_engine: HumanInTheLoopEngine,
        protection_service: ContactProtectionService,
    ):
        self.matcher = matcher
        self.content_agent = content_agent
        self.hitl_engine = hitl_engine
        self.protection_service = protection_service

    def prepare_buyer_outreach_actions(self, deal: DealContext, buyers: List[EnhancedBuyerProfile], top_n: int = 1):
        """Finds top matches and submits outreach actions for approval."""
        matches = self.matcher.match(deal, buyers)

        for match in matches[:top_n]:
            if match.match_score < 50:  # Don't bother with low-scoring matches
                continue

            # Use the ContactProtectionService to check if outreach is allowed
            if not self.protection_service.is_outreach_allowed(match.buyer_profile, "org-A"): # Assuming a context for org
                continue

            draft = self.content_agent.generate_buyer_outreach_draft(deal, match.buyer_profile)

            action = ActionForApproval(
                action_type="BUYER_OUTREACH",
                recommendation=f"Contact buyer {match.buyer_profile.name} for deal {deal.deal_id}",
                reasoning=f"High match score ({match.match_score:.0f}). Reasons: {'; '.join(match.match_reasons)}",
                supporting_data={"deal_id": deal.deal_id, "buyer_id": match.buyer_profile.buyer_id},
                confidence_score=match.match_score / 100,
                action_payload={"to": match.buyer_profile.contact_info.email, "subject": draft.subject, "body": draft.body},
            )

            self.hitl_engine.submit_for_approval(action)
            self.protection_service._add_to_history("org-A", match.buyer_profile.buyer_id, action.action_id, "SUBMITTED_FOR_APPROVAL")


class ActionExecutionAgent:
    """
    Phase 35: Finds and executes approved outreach actions.
    """

    def __init__(
        self,
        hitl_engine: HumanInTheLoopEngine,
        comm_provider: CommunicationProvider,
        protection_service: ContactProtectionService,
    ):
        self.hitl_engine = hitl_engine
        self.comm_provider = comm_provider
        self.protection_service = protection_service
        self.executed_action_ids: Set[str] = set()

    def execute_approved_actions(self):
        """Finds and processes all actions with an 'APPROVED' status."""
        approved_actions = [
            action
            for action in self.hitl_engine.approval_queue
            if action.status == ApprovalStatus.APPROVED and action.action_id not in self.executed_action_ids
        ]

        for action in approved_actions:
            try:
                result = self.comm_provider.send(action.action_payload)
                if result.status == "sent":
                    action.status = ApprovalStatus.EXECUTED
                    action._add_audit_entry(ApprovalStatus.EXECUTED, f"Action executed. Message ID: {result.external_message_id}", "ExecutionAgent")
                else:
                    raise ConnectionError(result.error_message)
            except Exception as e:
                action.status = ApprovalStatus.FAILED
                action._add_audit_entry(ApprovalStatus.FAILED, f"Execution failed: {e}", "ExecutionAgent")
            finally:
                # Mark as processed to prevent duplicate execution
                self.executed_action_ids.add(action.action_id)
                # Assuming org context is available
                self.protection_service._add_to_history("org-A", action.supporting_data.get("buyer_id"), action.action_id, action.status.value)