from __future__ import annotations

from typing import Any, Dict, List


class AcquisitionExceptionResolutionEngine:
    """
    Determines the appropriate resolution path for acquisition
    progress classifications generated by Sprint 4 Part 25.
    """

    STATUS = "ACQUISITION_EXCEPTION_RESOLUTION_GENERATED"

    def resolve(self, progress_analyses: List[Dict[str, Any]]) -> Dict[str, Any]:
        resolutions: List[Dict[str, Any]] = []

        for analysis in progress_analyses:
            resolutions.append(self._resolve_analysis(analysis))

        return {
            "resolutions": resolutions,
            "summary": self._build_summary(resolutions),
            "status": self.STATUS,
        }

    def _resolve_analysis(self, analysis: Dict[str, Any]) -> Dict[str, Any]:
        deal_id = analysis.get("deal_id")
        progress_status = analysis.get("progress_status")
        exception_type = analysis.get("exception_type")
        current_milestone = analysis.get("current_milestone")
        execution_state = analysis.get("execution_state")

        if progress_status == "BLOCKED":
            return {
                "deal_id": deal_id,
                "progress_status": progress_status,
                "exception_type": exception_type,
                "execution_state": execution_state,
                "current_milestone": current_milestone,
                "resolution_type": "BLOCKED_ACQUISITION_RESOLUTION",
                "resolution_action": "RESOLVE_BLOCKING_CONDITION",
                "resolution_status": "ACTION_REQUIRED",
                "next_step": (
                    "Identify and resolve the blocking condition before "
                    "advancing the acquisition."
                ),
                "requires_human_review": True,
                "status": self.STATUS,
            }

        if progress_status == "STALLED":
            return {
                "deal_id": deal_id,
                "progress_status": progress_status,
                "exception_type": exception_type,
                "execution_state": execution_state,
                "current_milestone": current_milestone,
                "resolution_type": "STALLED_ACQUISITION_RECOVERY",
                "resolution_action": "RECOVER_STALLED_ACQUISITION",
                "resolution_status": "ACTION_REQUIRED",
                "next_step": (
                    "Investigate the stalled milestone and initiate "
                    "a recovery action."
                ),
                "requires_human_review": True,
                "status": self.STATUS,
            }

        if progress_status == "REVIEW_REQUIRED":
            return {
                "deal_id": deal_id,
                "progress_status": progress_status,
                "exception_type": exception_type,
                "execution_state": execution_state,
                "current_milestone": current_milestone,
                "resolution_type": "HUMAN_REVIEW",
                "resolution_action": "ROUTE_TO_HUMAN_REVIEW",
                "resolution_status": "REVIEW_REQUIRED",
                "next_step": (
                    "Route the acquisition to human review before "
                    "additional execution occurs."
                ),
                "requires_human_review": True,
                "status": self.STATUS,
            }

        if progress_status == "READY_TO_ADVANCE":
            return {
                "deal_id": deal_id,
                "progress_status": progress_status,
                "exception_type": exception_type,
                "execution_state": execution_state,
                "current_milestone": current_milestone,
                "resolution_type": "MILESTONE_ADVANCEMENT",
                "resolution_action": "ADVANCE_ACQUISITION_MILESTONE",
                "resolution_status": "READY",
                "next_step": (
                    "Advance the acquisition to the next milestone."
                ),
                "requires_human_review": False,
                "status": self.STATUS,
            }

        return {
            "deal_id": deal_id,
            "progress_status": progress_status or "NORMAL_PROGRESS",
            "exception_type": exception_type,
            "execution_state": execution_state,
            "current_milestone": current_milestone,
            "resolution_type": "NORMAL_ACQUISITION_CONTINUATION",
            "resolution_action": "CONTINUE_CURRENT_MILESTONE",
            "resolution_status": "NO_EXCEPTION",
            "next_step": (
                "Continue execution of the current acquisition milestone."
            ),
            "requires_human_review": False,
            "status": self.STATUS,
        }

    @staticmethod
    def _build_summary(
        resolutions: List[Dict[str, Any]],
    ) -> Dict[str, int]:
        return {
            "total_resolutions": len(resolutions),
            "blocked_resolution_count": sum(
                1
                for item in resolutions
                if item["resolution_type"]
                == "BLOCKED_ACQUISITION_RESOLUTION"
            ),
            "stalled_resolution_count": sum(
                1
                for item in resolutions
                if item["resolution_type"]
                == "STALLED_ACQUISITION_RECOVERY"
            ),
            "human_review_count": sum(
                1
                for item in resolutions
                if item["requires_human_review"]
            ),
            "ready_to_advance_count": sum(
                1
                for item in resolutions
                if item["resolution_type"]
                == "MILESTONE_ADVANCEMENT"
            ),
            "normal_continuation_count": sum(
                1
                for item in resolutions
                if item["resolution_type"]
                == "NORMAL_ACQUISITION_CONTINUATION"
            ),
        }
        