from __future__ import annotations

from typing import Any, Dict, List


class AuthorizedAcquisitionActionExecutor:
    """
    Sprint 4 Part 28

    Executes only acquisition actions that have already been authorized
    by the Part 27 action-execution intelligence layer.

    This component is intentionally conservative:
    - Automatic continuation is allowed.
    - Automatic milestone advancement is allowed.
    - Blocking-condition resolution requires human action.
    - Stalled-acquisition recovery requires human action.
    - Human-review routing requires human action.

    No external seller communication, contracts, payments, or other
    real-world side effects are performed here.
    """

    AUTOMATED_ACTIONS = {
        "CONTINUE_CURRENT_MILESTONE",
        "ADVANCE_ACQUISITION_MILESTONE",
    }

    HUMAN_ACTIONS = {
        "RESOLVE_BLOCKING_CONDITION",
        "RECOVER_STALLED_ACQUISITION",
        "ROUTE_TO_HUMAN_REVIEW",
    }

    MILESTONE_SEQUENCE = [
        "EXECUTION_INITIATED",
        "SELLER_CONTACT",
        "PROPERTY_DUE_DILIGENCE",
        "NEGOTIATION",
        "PURCHASE_AGREEMENT",
        "ACQUISITION_COMPLETED",
    ]

    def execute(
        self,
        execution_results: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Execute authorized acquisition actions.

        Parameters
        ----------
        execution_results:
            Action execution decisions generated by Sprint 4 Part 27.

        Returns
        -------
        Dict[str, Any]
            Structured execution and state-transition results.
        """

        executions: List[Dict[str, Any]] = []
        automatic_executions: List[Dict[str, Any]] = []
        human_required: List[Dict[str, Any]] = []
        rejected: List[Dict[str, Any]] = []

        for action in execution_results:
            result = self._execute_action(action)

            executions.append(result)

            if result["execution_status"] == "EXECUTED":
                automatic_executions.append(result)
            elif result["execution_status"] == "HUMAN_ACTION_REQUIRED":
                human_required.append(result)
            elif result["execution_status"] == "REJECTED":
                rejected.append(result)

        return {
            "executions": executions,
            "automatic_executions": automatic_executions,
            "human_required": human_required,
            "rejected": rejected,
            "summary": {
                "total_actions": len(executions),
                "executed_count": len(automatic_executions),
                "human_action_count": len(human_required),
                "rejected_count": len(rejected),
            },
            "status": "AUTHORIZED_ACQUISITION_ACTION_EXECUTION_COMPLETE",
        }

    def _execute_action(self, action: Dict[str, Any]) -> Dict[str, Any]:
        deal_id = action.get("deal_id")
        resolution_action = action.get("resolution_action")
        current_milestone = action.get("current_milestone")
        progress_status = action.get("progress_status")
        requires_human_review = action.get("requires_human_review", False)
        automated_execution_allowed = action.get(
            "automated_execution_allowed",
            False,
        )

        base_result = {
            "deal_id": deal_id,
            "current_milestone": current_milestone,
            "resolution_action": resolution_action,
            "progress_status": progress_status,
        }

        if resolution_action in self.HUMAN_ACTIONS:
            return {
                **base_result,
                "execution_status": "HUMAN_ACTION_REQUIRED",
                "execution_type": "HUMAN_CONTROLLED_ACTION",
                "automated_execution_allowed": False,
                "requires_human_review": True,
                "state_transition": self._human_state_transition(
                    resolution_action
                ),
                "next_step": self._human_next_step(resolution_action),
                "status": "AUTHORIZED_ACTION_DEFERRED_TO_HUMAN",
            }

        if resolution_action not in self.AUTOMATED_ACTIONS:
            return {
                **base_result,
                "execution_status": "REJECTED",
                "execution_type": "UNAUTHORIZED_ACTION",
                "automated_execution_allowed": False,
                "requires_human_review": True,
                "state_transition": "NO_STATE_CHANGE",
                "next_step": "Reject the unrecognized acquisition action.",
                "status": "ACQUISITION_ACTION_REJECTED",
            }

        if requires_human_review or not automated_execution_allowed:
            return {
                **base_result,
                "execution_status": "HUMAN_ACTION_REQUIRED",
                "execution_type": "AUTHORIZATION_REQUIRED",
                "automated_execution_allowed": False,
                "requires_human_review": True,
                "state_transition": "NO_STATE_CHANGE",
                "next_step": (
                    "Obtain authorization before executing the acquisition action."
                ),
                "status": "AUTHORIZED_ACTION_DEFERRED_TO_HUMAN",
            }

        if resolution_action == "CONTINUE_CURRENT_MILESTONE":
            return self._execute_continuation(base_result)

        if resolution_action == "ADVANCE_ACQUISITION_MILESTONE":
            return self._execute_advancement(base_result)

        return {
            **base_result,
            "execution_status": "REJECTED",
            "execution_type": "UNAUTHORIZED_ACTION",
            "automated_execution_allowed": False,
            "requires_human_review": True,
            "state_transition": "NO_STATE_CHANGE",
            "next_step": "Reject the acquisition action.",
            "status": "ACQUISITION_ACTION_REJECTED",
        }

    def _execute_continuation(
        self,
        base_result: Dict[str, Any],
    ) -> Dict[str, Any]:
        return {
            **base_result,
            "execution_status": "EXECUTED",
            "execution_type": "AUTOMATED_CONTINUATION",
            "automated_execution_allowed": True,
            "requires_human_review": False,
            "state_transition": "ACQUISITION_REMAINS_ACTIVE",
            "next_milestone": base_result["current_milestone"],
            "next_step": (
                "Continue execution of the current acquisition milestone."
            ),
            "status": "ACQUISITION_ACTION_EXECUTED",
        }

    def _execute_advancement(
        self,
        base_result: Dict[str, Any],
    ) -> Dict[str, Any]:
        current_milestone = base_result["current_milestone"]

        if current_milestone not in self.MILESTONE_SEQUENCE:
            return {
                **base_result,
                "execution_status": "REJECTED",
                "execution_type": "INVALID_MILESTONE",
                "automated_execution_allowed": False,
                "requires_human_review": True,
                "state_transition": "NO_STATE_CHANGE",
                "next_step": (
                    "Reject advancement because the current milestone "
                    "is invalid."
                ),
                "status": "ACQUISITION_ACTION_REJECTED",
            }

        current_index = self.MILESTONE_SEQUENCE.index(current_milestone)

        if current_index >= len(self.MILESTONE_SEQUENCE) - 1:
            return {
                **base_result,
                "execution_status": "REJECTED",
                "execution_type": "ACQUISITION_ALREADY_COMPLETE",
                "automated_execution_allowed": False,
                "requires_human_review": True,
                "state_transition": "NO_STATE_CHANGE",
                "next_step": (
                    "Do not advance because acquisition is already complete."
                ),
                "status": "ACQUISITION_ACTION_REJECTED",
            }

        next_milestone = self.MILESTONE_SEQUENCE[current_index + 1]

        if next_milestone == "ACQUISITION_COMPLETED":
            state_transition = "ACQUISITION_COMPLETED"
        else:
            state_transition = "ACQUISITION_MILESTONE_ADVANCED"

        return {
            **base_result,
            "execution_status": "EXECUTED",
            "execution_type": "AUTOMATED_MILESTONE_ADVANCEMENT",
            "automated_execution_allowed": True,
            "requires_human_review": False,
            "state_transition": state_transition,
            "previous_milestone": current_milestone,
            "next_milestone": next_milestone,
            "next_step": (
                f"Acquisition advanced from {current_milestone} "
                f"to {next_milestone}."
            ),
            "status": "ACQUISITION_ACTION_EXECUTED",
        }

    @staticmethod
    def _human_state_transition(action: str) -> str:
        transitions = {
            "RESOLVE_BLOCKING_CONDITION": "ACQUISITION_REMAINS_BLOCKED",
            "RECOVER_STALLED_ACQUISITION": (
                "ACQUISITION_REMAINS_RECOVERY_REQUIRED"
            ),
            "ROUTE_TO_HUMAN_REVIEW": "ACQUISITION_REMAINS_REVIEW_REQUIRED",
        }

        return transitions.get(action, "NO_STATE_CHANGE")

    @staticmethod
    def _human_next_step(action: str) -> str:
        next_steps = {
            "RESOLVE_BLOCKING_CONDITION": (
                "Human intervention is required to resolve the blocking condition."
            ),
            "RECOVER_STALLED_ACQUISITION": (
                "Human intervention is required to recover the stalled acquisition."
            ),
            "ROUTE_TO_HUMAN_REVIEW": (
                "Human review is required before additional acquisition execution."
            ),
        }

        return next_steps.get(
            action,
            "Human intervention is required.",
        )