from __future__ import annotations

from typing import Any, Dict


class DecisionPolicyEnforcementEngine:
    """
    Applies an adaptive decision policy to individual deal evaluations.

    The engine does not create the policy. It enforces a policy that has
    already been generated by the adaptive decision-policy layer.
    """

    POLICY_VERSION = "1.0"

    def enforce(
        self,
        deal: Dict[str, Any],
        policy: Dict[str, Any],
    ) -> Dict[str, Any]:
        deal_id = str(deal.get("deal_id", "UNKNOWN"))
        recommendation = str(
            deal.get("recommendation", "PASS")
        ).upper()

        recommendation_score = self._safe_float(
            deal.get("recommendation_score", 0.0)
        )

        confidence_score = self._safe_float(
            deal.get("confidence_score", 0.0)
        )

        risk_level = str(
            deal.get("risk_level", "HIGH")
        ).upper()

        policy_action = str(
            policy.get("policy_action", "MAINTAIN_DEAL_SELECTION")
        ).upper()

        threshold_direction = str(
            policy.get("threshold_direction", "MAINTAIN")
        ).upper()

        confidence_adjustment = self._safe_float(
            policy.get("confidence_adjustment", 0.0)
        )

        adjusted_confidence = max(
            0.0,
            min(
                100.0,
                confidence_score + confidence_adjustment,
            ),
        )

        enforcement_decision = self._determine_decision(
            recommendation=recommendation,
            recommendation_score=recommendation_score,
            confidence_score=adjusted_confidence,
            risk_level=risk_level,
            policy_action=policy_action,
            threshold_direction=threshold_direction,
        )

        action = self._determine_action(enforcement_decision)

        return {
            "deal_id": deal_id,
            "policy_version": self.POLICY_VERSION,
            "policy_action": policy_action,
            "threshold_direction": threshold_direction,
            "original_confidence_score": confidence_score,
            "confidence_adjustment": confidence_adjustment,
            "adjusted_confidence_score": round(
                adjusted_confidence,
                2,
            ),
            "recommendation": recommendation,
            "recommendation_score": round(
                recommendation_score,
                2,
            ),
            "risk_level": risk_level,
            "enforcement_decision": enforcement_decision,
            "action": action,
            "status": "DECISION_POLICY_ENFORCED",
        }

    def _determine_decision(
        self,
        recommendation: str,
        recommendation_score: float,
        confidence_score: float,
        risk_level: str,
        policy_action: str,
        threshold_direction: str,
    ) -> str:
        """
        Determine whether the current deal passes the active policy.

        Policy thresholds are deliberately conservative. A deal must have
        both a strong recommendation and sufficient confidence to receive
        approval.
        """

        recommendation_threshold = 70.0
        confidence_threshold = 70.0

        if threshold_direction == "TIGHTEN":
            recommendation_threshold += 5.0
            confidence_threshold += 5.0

        elif threshold_direction == "RELAX":
            recommendation_threshold -= 5.0
            confidence_threshold -= 5.0

        if risk_level == "HIGH":
            return "REJECT"

        if recommendation != "PURSUE":
            if recommendation_score >= recommendation_threshold:
                return "REVIEW"

            return "REJECT"

        if (
            recommendation_score >= recommendation_threshold
            and confidence_score >= confidence_threshold
        ):
            if policy_action == "REVIEW_DEAL_SELECTION":
                return "REVIEW"

            return "APPROVE"

        if (
            recommendation_score >= recommendation_threshold - 10.0
            or confidence_score >= confidence_threshold - 10.0
        ):
            return "REVIEW"

        return "REJECT"

    @staticmethod
    def _determine_action(enforcement_decision: str) -> str:
        if enforcement_decision == "APPROVE":
            return "PROCEED_WITH_DEAL"

        if enforcement_decision == "REVIEW":
            return "REQUIRE_HUMAN_REVIEW"

        return "DO_NOT_PROCEED"

    @staticmethod
    def _safe_float(value: Any) -> float:
        try:
            return float(value)
        except (TypeError, ValueError):
            return 0.0